name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        cd src 
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        cd test 
        dotnet test
    - name: Build solution and generate NuGet package
      run: |  
          cd src
          dotnet pack -c Release -o out  
    - name: Push generated package to GitHub registry
      run: |
          cd src/out
          dotnet nuget push *.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/BookShelf/index.json
          
      
